# Generated by Django 3.0.8 on 2020-07-03 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
